### ISSUE TITLE
support: 

### ISSUE THREAD

**Issue by ahkazemi2007** [HamidMolareza/Quera#34]
# Support Question
https://quera.org/problemset/33034/
چرا برای حل این سوال وقتی من کد اولی رو میدم ۰ میده ولی دومی ۱۰۰ میده (اگر صلاح دونستید میتونید کد دومم رو به کدهای حلیتون اضافه کنید :) )
```python
def coloring(ls):
    alent = len(ls)
    blent = len(ls[0])
    clent = len(ls[0][0])

    mls = []
    for i in range(alent):
        tls1 = []
        for j in range(blent):
            tls2 = []
            for k in range(clent):
                if (
                    (i != 0 and i != alent - 1)
                    and (j >= 1 and j <= blent - 2)
                    and (k >= 1 and k <= clent - 2)
                ):
                    tls2.append(0)
                else:
                    tls2.append(1)
            tls1.append(tls2)
        mls.append(tls1)
    return mls
```
```python
def coloring(ls):
    alent = len(ls)
    blent = len(ls[0])
    clent = len(ls[0][0])

    for i in range(alent):
        for j in range(blent):
            for k in range(clent):
                if (
                    (i != 0 and i != alent - 1)
                    and (j >= 1 and j <= blent - 2)
                    and (k >= 1 and k <= clent - 2)
                ):
                    ls[i][j][k] = 0
                else:
                    ls[i][j][k] = 1
    return ls
```

**Comment by HamidMolareza** [comment]
در نکته سوم سوال گفته شده که تابع نباید مقداری رو چاپ یا برگردونه. باید لیستی که به تابع پاس داده شده رو تغییر بده.
در بسیاری از زبون‌ها، لیست‌ها و آرایه‌ها به صورت رفرنس پاس داده میشن نه خود اون‌ها. یعنی آدرس اون‌ها در حافظه پاس داده میشه نه کل آرایه. برای همین وقتی شما مقادیر رو در تابع تغییر می‌دین در حقیقت دارین مقادیر اصلی آرایه رو تغییر میدین.
اگر زمانی خواستین این اتفاق نیوفته، راهکارش اینه که توی فانکشن از آرایه کپی بگیرید که در این سوال نباید اینکار رو کنید.

برای اینکه راه‌حل به اسم خودتون ثبت بشه pull request  بفرستین.
ممنون.

**Comment by ahkazemi2007** [comment]
سلام ممنون بابت توضیحاتتون
من کار با گیت هاب رو زیاد بلد نیستم اگر میشه خودتون کد رو بزارید مهم نیست به اسم من باش فقط میخوام یه کمکی کرده باشم در مقابل کمک های زیاد شما

**Comment by HamidMolareza** [comment]
گیت (Git) ابزار خیلی مفید و مهمیه خصوصا اگر بخواین برنامه‌نویسی رو به صورت جدی دنبال کنید.
گیت‌هاب و گیت‌لب و... هم براساس گیت کار میکنن.
این مورد میتونه تمرین خوبی برای شروع باشه.
مطلب رایگان درموردش زیاده. یکی دو ساعته میتونید مفاهیم اصلیش رو یاد بگیرید. بعد با چندتا دستور PR بزنید. مثلا:

```
git clone https://github.com/HamidMolareza/QueraProblems
git checkout -b solve-33034
[Make Changes](https://github.com/HamidMolareza/QueraProblems#usage)
git add .
git commit -m "solve(33034): python"
git push origin my-feature-branch
Send PR from GitHub
```
به صورت خلاصه اول پروژه رو clone می‌کنید بعد یه شاخه جدید می‌سازید بعد تغییرات رو اعمال می‌کنید بعد کامیت و پوش می‌کنید. در آخر گیت‌هاب تغییرات رو تشخیص میده و به صورت دستی با UI میتونید درخواست PR رو بفرستین.

حداقل یکی دو هفته این ایشو رو باز میذارم تا فرصت داشته باشین بعدش اگر مایل نبودین خودم اینکار رو میکنم.
ممنون.
