### ISSUE TITLE
support: 

### ISSUE THREAD

**Issue by ahkazemi2007** [HamidMolareza/Quera#35]
``# Support Question
https://github.com/HamidMolareza/QueraProblems/blob/master/Solutions/18310/python3/program.py

سلا م برای این قسمت من راه حل زیر رو زدم و کار کرد و من یک سوال داشتم که راه حل من تمیزتر حساب میشه یا شانسی
```python
s = input()
p = input()
s += s * 50

if p in s:
    print("Yes")
else:
    print("No")
```

**Comment by HamidMolareza** [comment]
سلام
جالبه :)
یه جورایی بیشتر کلکه ولی خب راه‌حل مسئله کوئرا (نه کلی) هم هستش.
سوال اصلی اینه که عدد ۵۰ رو از کجا آوردین؟ یه عدد نسبتا بزرگ هستش که تست کیس‌های کوئرا رو ممکنه رد کنه ولی مطمئنا تمامی حالت‌ها رو جوابگو نیست.
خودتون می‌تونید پارامتر دوم رو اینقدر بزرگ بدین که جواب اشتباه بده.
ولی روش خوبی میتونه باشه. می‌تونید اون ۵۰ رو متغیر کنید.
اگر این دوتا رشته وجهه اشتراک نداشته باشن که هیچ. ولی اگر کاراکترهای مشترک داشته باشن می‌تونیم به تعداد اختلاف طول کاراکترها ضرب کنیم تا مطمئن بشیم رشته اول ما به قدر کافی بزرگ شده. مثلا میشه کد زیر رو امتحان کرد:
```python
s = input()
p = input()
s += s * abs(len(p) - len(s))

if p in s:
    print("Yes")
else:
    print("No")
```
تابع `abs` هم قدرمطلق هستش برای زمانی که طول رشته دوم کوچیک‌تر از اولی باشه.
