### ISSUE TITLE
Refactor request: 134354

### ISSUE THREAD

**Issue by ARiYaNSEp0-0** [HamidMolareza/Quera#46]
I think using async/await for this problem it's better here is the final code : 

```js
function timeit(fn) {
  return async (...args) => {
    try {
      const beforeExecution = performance.now();
      const fnResult = await fn(...args);
      const afterExecution = performance.now();
      return { value: fnResult, time: afterExecution - beforeExecution };
    } catch (err) {
      return { value: err };
    }
  };
}
```

**Comment by HamidMolareza** [comment]
For the source file name, make sure to use **main.js** so that Quera's system doesn’t encounter any issues.

**Comment by HamidMolareza** [comment]
I've added you to the list of contributors (you've probably received an email for confirmation).  
From now, you can push directly to the repository.  

However, the main branch (master) is protected and can only be merged via a PR. This means you'll need to make changes in a separate branch (like `dev` or any name you prefer) and then create a PR for the master branch.

**Comment by ARiYaNSEp0-0** [comment]
Thank you so much. I really appreciate this repository because one of the main issues I have with Quera is that they don't provide solutions for all challenges. For those who really want to learn, this can be a bit of a problem. This repository is excellent at solving that issue. In comparison to other similar repositories (Quera solutions), this one has the best contribution system. Thanks!

**Comment by HamidMolareza** [comment]
I'm glad it was helpful for you.
